[package]
name = "bubbleproc-linux"
version = "0.1.0"
edition = "2021"

[dependencies]
bubbleproc-core = { path = "../bubbleproc-core" }
which = "5.0"
shellexpand = "3.0"
# For checking GPU devices
glob = "0.3" 
